def create():
    f=open("bus.txt","w")
    ("good day")
    f.write("\n")
    f.write("These are the buses that are associated with our company")
    f.write("\n")
    f.write("Bus A")
    f.write("\n")
    f.write("One of the oldest joined company been in service for about 3 years")
    f.write("\n")
    f.write("skilled driver")
    f.write("\n")
    f.write("friendly staff")
    f.write("\n")
    f.write("5 star rating")
    f.write("\n")
    f.write("no stopping")
    f.write("\n")
    f.write("but in between 10 min break is allowed every 3 hours")
    f.write("\n")
    f.write("\n")
    f.write("Bus B")
    f.write("\n")
    f.write("Been in service for 2 years")
    f.write("\n")
    f.write("4.7 star rating")
    f.write("\n")
    f.write("1 stop")
    f.write("\n")
    f.write("waits for 30 min in the refreshment centre")
    f.write("\n")
    f.write("\n")
    f.write("Bus C ")
    f.write("\n")
    f.write("Been in service for 1.5 years")
    f.write("\n")
    f.write("4.5 star rating")
    f.write("\n")
    f.write("2 stops")
    f.write("\n")
    f.write("waits for 30 min at refreshment centre")
    f.write("\n")
    f.write("\n")
    f.write("Bus D")
    f.write("\n")
    f.write("4.3 star rating")
    f.write("\n")
    f.write("Been in service for 1 year")
    f.write("\n")
    f.write("3 stops")
    f.write("\n")
    f.write("waits for 25 minutes")
    f.write("\n")
    f.write("\n")
    f.write("Bus E")
    f.write("\n")
    f.write("Been in service for 1 year")
    f.write("\n")
    f.write("4star rating")
    f.write("\n")
    f.write("4 stops")
    f.write("\n")
    f.write("waits for 20 minutes")
    f.close()
CREATE()
    
