def create():
    g=open("location.txt","w")
    g.write("good day")
    g.write("\n")
    g.write("These are the locations that are associated with our buses")
    g.write("\n")
    g.write("Chennai to Coimbatore")
    g.write("\n")
    g.write("Bus A,B,C")
    g.write("\n")
    g.write("\n")
    g.write("Chennai to Hyderabad")
    g.write("\n")
    g.write("Bus A,D,E")
    g.write("\n")
    g.write("\n")
    g.write("Chennai to Madurai")
    g.write("\n")
    g.write("Bus A,B,E")
    g.write("\n")
    g.write("\n")
    g.write("madurai to coimbatore")
    g.write("\n")
    g.write("Bus A,D,C")
    g.write("\n")
    g.write("\n")
    g.write("Madurai to chennai")
    g.write("\n")
    g.write("Bus A,B,D")
    g.write("\n")
    g.write("\n")
    g.write("Coimbatore to Madurai")
    g.write("\n")
    g.write("Bus C,D,E")
    g.write("\n")
    g.write("\n")
    g.write("Coimbatore to Hyderabad")
    g.write("\n")
    g.write("Bus B,D,E")
    g.write("\n")
    g.write("\n")
    g.write("Madurai to coimbatore")
    g.write("\n")
    g.write("Bus E,B,C")
    g.write("\n")
    g.write("\n")
    g.close()
CREATE()
